### ISSUE TITLE
Demo crashes

### ISSUE THREAD

**Issue by mergesort** [remirobert/Kinder#1]
It crashes on this:

```
newCard.image = UIImage(data: NSData(contentsOfURL: NSURL(string: "http://thecatapi.com/api/images/get?format=src&type=gif")!)!)`
```

The error is: `fatal error: unexpectedly found nil while unwrapping an Optional value`

I think it's possible that the API might not return an image in some condition, but I haven't looked into it.

There's also a crash on:

```
button.setImage(UIImage(named: "cancel")!.imageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate), forState: UIControlState.Normal)
```

The error is `fatal error: unexpectedly found nil while unwrapping an Optional value`

For this one, it looks like in the demo project, the cancel asset just wasn't committed.

**Comment by remirobert** [comment]
i fix the example project. I didn't get any error with the API, but it's possible if you don't have internet access or something like, it would crash.

**Comment by mergesort** [comment]
I do have internet access. It sometimes fails, and sometimes doesn't, based on whether it was able to fetch data.
